(defparameter *student-name* "")
(defparameter *student-class* "")
(defparameter *image-query* nil)
(defparameter *base-color* nil)
(defparameter *color-complement* nil)
(defparameter *color-type* "Dark")
(defparameter *alpha-scale* "0.5")
(defparameter *paper-size* (make-plane* 2480 3508))
